services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/2181'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: ["pinot-network"]

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
        zookeeper:
            condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks: ["pinot-network"]

  pinot-controller:
    image: apachepinot/pinot:1.2.0
    container_name: pinot-controller
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/9000'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "StartController"
      - "-zkAddress"
      - "zookeeper:2181"
    networks: ["pinot-network"]

  pinot-broker:
    image: apachepinot/pinot:1.2.0
    container_name: pinot-broker
    restart: unless-stopped
    depends_on:
      pinot-controller:
        condition: service_healthy
    ports:
      - "8099:8099"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/8099'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "StartBroker"
      - "-zkAddress"
      - "zookeeper:2181"
    networks: ["pinot-network"]

  pinot-server:
    image: apachepinot/pinot:1.2.0
    container_name: pinot-server
    restart: unless-stopped
    depends_on:
      pinot-broker:
        condition: service_healthy
    ports:
      - "8098:8098"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/8098'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "StartServer"
      - "-zkAddress"
      - "zookeeper:2181"
    networks: ["pinot-network"]

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8081:8080"
    volumes:
      - ./trino-config:/etc/trino:ro
    networks: ["pinot-network"]

  superset:
    build:
      context: ./superset
    image: custom-superset:latest
    container_name: superset
    depends_on:
      - trino
    environment:
      SUPERSET_SECRET_KEY: "thisISaSECRET_1234"
      FLASK_APP: superset
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@superset.com
    ports:
      - "8088:8088"
    networks: ["pinot-network"]

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: kafka-producer
    depends_on: ["kafka"]
    networks: ["pinot-network"]

volumes:
  trino-config: {}

networks:
  pinot-network:
    driver: bridge
