source:
  type: postgres
  hostname: postgres
  port: 5432
  username: retail_user
  password: retail_pass
  database-name: retail_db
  schema-name: public
  tables: public\.orders
  slot.name: flink_slot_v2
  decoding.plugin.name: pgoutput
  scan.startup.mode: initial

sink:
  type: starrocks
  jdbc-url:  jdbc:mysql://starrocks-quickstart:9030
  load-url:  http://starrocks-quickstart:8030
  username: root
  password: ""
  database-name: retail
  table.create.properties.replication_num: 1

pipeline:
  name: Postgres→StarRocks
  parallelism: 1
