# Đẩy các bản ghi lỗi (total_amount<=0 hoặc status IS NULL), thêm cột error_reason
pipeline:
  name: Postgres to StarRocks (error)
  parallelism: 1

source:
  type: postgres
  hostname: postgres
  port: 5432
  username: retail_user
  password: retail_pass
  database-name: retail_db
  schema-name: public
  tables: public\.orders
  slot-name: flink_slot_error
  decoding.plugin.name: pgoutput
  scan.startup.mode: initial

transform:
  - source-table: public\.orders
    filter: total_amount <= 0 OR status IS NULL
    description: Lọc bản ghi lỗi
  - source-table: public\.orders
    projection: >
      *,
      CASE
        WHEN total_amount <= 0 THEN 'invalid amount'
        WHEN status IS NULL THEN 'missing status'
        ELSE 'unknown'
      END AS error_reason
    description: Thêm cột error_reason

sink:
  type: starrocks
  jdbc-url: jdbc:mysql://starrocks-quickstart:9030
  load-url: http://starrocks-quickstart:8030
  database-name: retail
  table-name: ods_orders_error
  username: root
  password: ""
  sink.properties.format: json
  sink.properties.strip_outer_array: true
