# Đẩy các bản ghi hợp lệ (total_amount>0 và status IS NOT NULL)
pipeline:
  name: Postgres to StarRocks (clean)
  parallelism: 1

source:
  type: postgres
  hostname: postgres
  port: 5432
  username: retail_user
  password: retail_pass
  database-name: retail_db
  schema-name: public
  tables: public\.orders
  slot-name: flink_slot_clean
  decoding.plugin.name: pgoutput
  scan.startup.mode: initial

transform:
  - source-table: public\.orders
    filter: total_amount > 0 AND status IS NOT NULL
    description: Lọc các đơn có total_amount>0 và status không NULL

sink:
  type: starrocks
  jdbc-url: jdbc:mysql://starrocks-quickstart:9030
  load-url: http://starrocks-quickstart:8030
  database-name: retail
  table-name: ods_orders_clean
  username: root
  password: ""
  sink.properties.format: json
  sink.properties.strip_outer_array: true
